### ISSUE TITLE
Update the bitcoin logo

### ISSUE THREAD

**Issue by aha999** [nduhamell/bitcoin-donate-button#1]
Update the bitcoin logo in the button to the newest one:
Official SVG: https://bitcoin.org/img/icons/logotop.svg

Something like this (with the Donate text instead of Accepted Here): 
http://donatebitcoin.io/wp-content/uploads/2017/07/bitcoinaccept-1.png
from http://donatebitcoin.io/button/
![slika](https://user-images.githubusercontent.com/50620416/72663090-a4e9b200-39ee-11ea-9aa7-92ee8f1f9df3.png)

Or like this: 
https://sourceforge.net/projects/bitcoin-button/
![slika](https://user-images.githubusercontent.com/50620416/72663132-26414480-39ef-11ea-904e-7e5218e2aada.png)

Found some more buttons: https://iconscout.com/icon/bitcoin-378

**Comment by nduhamell** [comment]
Feel free to make these changes yourself, all projects are meant as a baseline and with an MIT license you are free to edit and do with it as you please, commercial or not. You don't even have to give me credit if you don't want, have a great day ;) stay curious!
