### ISSUE TITLE
One of your links is not working 

### ISSUE THREAD

**Issue by aha999** [nduhamell/bitcoin-donate-button#3]
On the main site, the link is broken 404: https://gitub.nated.xyz/donate/

**Comment by nduhamell** [comment]
Thanks! That site was deprecated, I now use a new one. I went ahead and made Permanent Redirects to point to the new site, any variation of that URL, with a subdomain that is, will now go to the new site with all my projects and docs: https://nateduhamell.com

Have a great night!!
